const SHOP_DATA = [
  {
    title: "Jagermeister original",
    items: [
      {
        id: 1,
        imageUrl: "https://i.ibb.co/yhfvq8b/original20ml.png",
        name: "Jagermeister original 20ml Việt Nam",
        quantity: 100,
        price: "60.000VNĐ",
        vol: "20ml",
        alcoholContent: "35%",
        type: "Kräuterlikör",
      },
      {
        id: 2,
        imageUrl: "https://i.ibb.co/VSzjzSM/original200ml.png",
        name: "Jagermeister original 200ml Việt Nam",
        quantity: 100,
        price: "280.000VNĐ",
        vol: "200ml",
        alcoholContent: "35%",
        type: "Kräuterlikör",
      },
      {
        id: 3,
        imageUrl: "https://i.ibb.co/V2Jqrcp/original700ml.png",
        name: "Jagermeister original 700ml Việt Nam",
        quantity: 100,
        price: "430.000VNĐ",
        vol: "700ml",
        alcoholContent: "35%",
        type: "Kräuterlikör",
      },
      {
        id: 4,
        imageUrl: "https://i.ibb.co/j3hhSzc/original1000ml.png",
        name: "Jagermeister original 1000ml Việt Nam",
        quantity: 100,
        price: "530.000VNĐ",
        vol: "1000ml",
        alcoholContent: "35%",
        type: "Kräuterlikör",
      },
      {
        id: 5,
        imageUrl: "https://i.ibb.co/fQ67tG1/original100ml.png",
        name: "Jagermeister original 100ml xách tay Đức",
        quantity: 100,
        price: "400.000VNĐ",
        vol: "100ml",
        alcoholContent: "35%",
        type: "Kräuterlikör",
      },
      {
        id: 6,
        imageUrl: "https://i.ibb.co/V2Jqrcp/original700ml.png",
        name: "Jagermeister original 700ml xách tay Đức",
        quantity: 100,
        price: "1.300.000VNĐ",
        vol: "700ml",
        alcoholContent: "35%",
        type: "Kräuterlikör",
      },
      {
        id: 7,
        imageUrl: "https://i.ibb.co/j3hhSzc/original1000ml.png",
        name: "Jagermeister original 1000ml xách tay Đức",
        quantity: 0,
        price: "1.900.000VNĐ",
        vol: "1000ml",
        alcoholContent: "35%",
        type: "Kräuterlikör",
      },
    ],
  },

  {
    title: "Jagermeister special",
    items: [
      {
        id: 1,
        imageUrl: "https://i.ibb.co/Kqw9ck5/coldbrew20ml.png",
        name: "Jagermeister Coldbrew 20ml",
        quantity: 100,
        price: "180.000VNĐ",
        vol: "20ml",
        alcoholContent: "33%",
        type: "Kräuterlikör",
      },
      {
        id: 2,
        imageUrl: "https://i.ibb.co/8MFf7dH/coldbrew1000ml.png",
        name: "Jagermeister Coldbrew 1000ml",
        quantity: 100,
        price: "2.500.000VNĐ",
        vol: "1000ml",
        alcoholContent: "33%",
        type: "Kräuterlikör",
      },
      {
        id: 3,
        imageUrl: "https://i.ibb.co/zRCXYMR/spice700ml.png",
        name: "Jagermeister Spice 700ml",
        quantity: 2,
        price: "2.500.000VNĐ",
        vol: "700ml",
        alcoholContent: "25%",
        type: "Kräuterlikör",
      },
      {
        id: 4,
        imageUrl: "https://i.ibb.co/YQpqxQC/scharf700ml.png",
        name: "Jagermeister Scharf 700ml",
        quantity: 8,
        price: "1.900.000VNĐ",
        vol: "700ml",
        alcoholContent: "33%",
        type: "Kräuterlikör",
      },
      {
        id: 5,
        imageUrl: "https://i.ibb.co/Q6N31gj/Manifest40ml.png",
        name: "Jagermeister Manifest 40ml",
        quantity: 8,
        price: "450.000VNĐ",
        vol: "40ml",
        alcoholContent: "38%",
        type: "Kräuterlikör",
      },
      {
        id: 6,
        imageUrl: "https://i.ibb.co/DtpdX3x/Manifest1000ml.png",
        name: "Jagermeister Manifest 1000ml",
        quantity: 8,
        price: "3.000.000VNĐ",
        vol: "1000ml",
        alcoholContent: "38%",
        type: "Kräuterlikör",
      },
    ],
  },
];

export default SHOP_DATA;
